{-
   Persona
   KSF Media unified login service

   The version of the OpenAPI document: 1.3.0

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git
   Do not edit this file manually.
-}


module Request.Entitlements exposing (entitlementsGet)

import Dict
import Http
import Json.Decode as Decode
import Url.Builder as Url




basePath : String
basePath =
    "https://persona.api.ksfmedia.fi/v1"


entitlementsGet :
    { onSend : Result Http.Error (Dict.Dict String String) -> msg





    }
    -> Cmd msg
entitlementsGet params =
    Http.request
        { method = "GET"
        , headers = []
        , url = Url.crossOrigin basePath
            ["entitlements"]
            []
        , body = Http.emptyBody
        , expect = Http.expectJson params.onSend (Decode.dict Decode.string)
        , timeout = Just 30000
        , tracker = Nothing
        }
