{-
   Persona
   KSF Media unified login service

   The version of the OpenAPI document: 1.3.0

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git
   Do not edit this file manually.
-}


module Data.ActiveDays exposing (ActiveDays, decoder, encode)

import Dict exposing (Dict)
import Json.Decode as Decode exposing (Decoder)
import Json.Decode.Pipeline exposing (optional, required)
import Json.Encode as Encode


type alias ActiveDays =
    { mon : Bool
    , tue : Bool
    , wed : Bool
    , thu : Bool
    , fri : Bool
    , sat : Bool
    , sun : Bool
    }


decoder : Decoder ActiveDays
decoder =
    Decode.succeed ActiveDays
        |> required "mon" Decode.bool
        |> required "tue" Decode.bool
        |> required "wed" Decode.bool
        |> required "thu" Decode.bool
        |> required "fri" Decode.bool
        |> required "sat" Decode.bool
        |> required "sun" Decode.bool



encode : ActiveDays -> Encode.Value
encode model =
    Encode.object
        [ ( "mon", Encode.bool model.mon )
        , ( "tue", Encode.bool model.tue )
        , ( "wed", Encode.bool model.wed )
        , ( "thu", Encode.bool model.thu )
        , ( "fri", Encode.bool model.fri )
        , ( "sat", Encode.bool model.sat )
        , ( "sun", Encode.bool model.sun )

        ]


