{-
   Persona
   KSF Media unified login service

   The version of the OpenAPI document: 1.3.0

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git
   Do not edit this file manually.
-}


module Data.Address exposing (Address, decoder, encode)

import Dict exposing (Dict)
import Json.Decode as Decode exposing (Decoder)
import Json.Decode.Pipeline exposing (optional, required)
import Json.Encode as Encode


type alias Address =
    { countryCode : String
    , zipCode : Maybe (String)
    , city : Maybe (String)
    , streetAddress : String
    , streetName : Maybe (String)
    , houseNo : Maybe (String)
    , staircase : Maybe (String)
    , apartment : Maybe (String)
    }


decoder : Decoder Address
decoder =
    Decode.succeed Address
        |> required "countryCode" Decode.string
        |> optional "zipCode" (Decode.nullable Decode.string) Nothing
        |> optional "city" (Decode.nullable Decode.string) Nothing
        |> required "streetAddress" Decode.string
        |> optional "streetName" (Decode.nullable Decode.string) Nothing
        |> optional "houseNo" (Decode.nullable Decode.string) Nothing
        |> optional "staircase" (Decode.nullable Decode.string) Nothing
        |> optional "apartment" (Decode.nullable Decode.string) Nothing



encode : Address -> Encode.Value
encode model =
    Encode.object
        [ ( "countryCode", Encode.string model.countryCode )
        , ( "zipCode", Maybe.withDefault Encode.null (Maybe.map Encode.string model.zipCode) )
        , ( "city", Maybe.withDefault Encode.null (Maybe.map Encode.string model.city) )
        , ( "streetAddress", Encode.string model.streetAddress )
        , ( "streetName", Maybe.withDefault Encode.null (Maybe.map Encode.string model.streetName) )
        , ( "houseNo", Maybe.withDefault Encode.null (Maybe.map Encode.string model.houseNo) )
        , ( "staircase", Maybe.withDefault Encode.null (Maybe.map Encode.string model.staircase) )
        , ( "apartment", Maybe.withDefault Encode.null (Maybe.map Encode.string model.apartment) )

        ]


