{-
   Persona
   KSF Media unified login service

   The version of the OpenAPI document: 1.3.0

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git
   Do not edit this file manually.
-}


module Data.Campaign exposing (Campaign, decoder, encode)

import Dict exposing (Dict)
import Json.Decode as Decode exposing (Decoder)
import Json.Decode.Pipeline exposing (optional, required)
import Json.Encode as Encode


type alias Campaign =
    { no : Int
    , id : String
    , name : String
    }


decoder : Decoder Campaign
decoder =
    Decode.succeed Campaign
        |> required "no" Decode.int
        |> required "id" Decode.string
        |> required "name" Decode.string



encode : Campaign -> Encode.Value
encode model =
    Encode.object
        [ ( "no", Encode.int model.no )
        , ( "id", Encode.string model.id )
        , ( "name", Encode.string model.name )

        ]


