{-
   Persona
   KSF Media unified login service

   The version of the OpenAPI document: 1.3.0

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git
   Do not edit this file manually.
-}


module Data.DeliveryAddress exposing (DeliveryAddress, decoder, encode)

import Dict exposing (Dict)
import Json.Decode as Decode exposing (Decoder)
import Json.Decode.Pipeline exposing (optional, required)
import Json.Encode as Encode


type alias DeliveryAddress =
    { streetAddress : Maybe (String)
    , zipcode : String
    , city : Maybe (String)
    }


decoder : Decoder DeliveryAddress
decoder =
    Decode.succeed DeliveryAddress
        |> optional "streetAddress" (Decode.nullable Decode.string) Nothing
        |> required "zipcode" Decode.string
        |> optional "city" (Decode.nullable Decode.string) Nothing



encode : DeliveryAddress -> Encode.Value
encode model =
    Encode.object
        [ ( "streetAddress", Maybe.withDefault Encode.null (Maybe.map Encode.string model.streetAddress) )
        , ( "zipcode", Encode.string model.zipcode )
        , ( "city", Maybe.withDefault Encode.null (Maybe.map Encode.string model.city) )

        ]


