{-
   Persona
   KSF Media unified login service

   The version of the OpenAPI document: 1.3.0

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git
   Do not edit this file manually.
-}


module Data.DescriptionFrequency exposing (DescriptionFrequency, decoder, encode)

import Dict exposing (Dict)
import Json.Decode as Decode exposing (Decoder)
import Json.Decode.Pipeline exposing (optional, required)
import Json.Encode as Encode


type alias DescriptionFrequency =
    { amount : Int
    , unit : String
    }


decoder : Decoder DescriptionFrequency
decoder =
    Decode.succeed DescriptionFrequency
        |> required "amount" Decode.int
        |> required "unit" Decode.string



encode : DescriptionFrequency -> Encode.Value
encode model =
    Encode.object
        [ ( "amount", Encode.int model.amount )
        , ( "unit", Encode.string model.unit )

        ]


