{-
   Persona
   KSF Media unified login service

   The version of the OpenAPI document: 1.3.0

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git
   Do not edit this file manually.
-}


module Data.GdprConsent exposing (GdprConsent, decoder, encode)

import Dict exposing (Dict)
import Json.Decode as Decode exposing (Decoder)
import Json.Decode.Pipeline exposing (optional, required)
import Json.Encode as Encode


type alias GdprConsent =
    { brand : String
    , consentKey : String
    , value : Bool
    }


decoder : Decoder GdprConsent
decoder =
    Decode.succeed GdprConsent
        |> required "brand" Decode.string
        |> required "consentKey" Decode.string
        |> required "value" Decode.bool



encode : GdprConsent -> Encode.Value
encode model =
    Encode.object
        [ ( "brand", Encode.string model.brand )
        , ( "consentKey", Encode.string model.consentKey )
        , ( "value", Encode.bool model.value )

        ]


