{-
   Persona
   KSF Media unified login service

   The version of the OpenAPI document: 1.3.0

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git
   Do not edit this file manually.
-}


module Data.InlineResponse415UnsupportedMediaType exposing (InlineResponse415UnsupportedMediaType, Description(..), decoder, encode)

import Dict exposing (Dict)
import Json.Decode as Decode exposing (Decoder)
import Json.Decode.Pipeline exposing (optional, required)
import Json.Encode as Encode


type alias InlineResponse415UnsupportedMediaType =
    { description : Maybe (Description)
    }


type Description
    = UnsupportedMediaType



decoder : Decoder InlineResponse415UnsupportedMediaType
decoder =
    Decode.succeed InlineResponse415UnsupportedMediaType
        |> optional "description" (Decode.nullable descriptionDecoder) Nothing



encode : InlineResponse415UnsupportedMediaType -> Encode.Value
encode model =
    Encode.object
        [ ( "description", Maybe.withDefault Encode.null (Maybe.map encodeDescription model.description) )

        ]



descriptionDecoder : Decoder Description
descriptionDecoder =
    Decode.string
        |> Decode.andThen
            (\str ->
                case str of
                    "Unsupported media type" ->
                        Decode.succeed UnsupportedMediaType

                    other ->
                        Decode.fail <| "Unknown type: " ++ other
            )



encodeDescription : Description -> Encode.Value
encodeDescription model =
    case model of
        UnsupportedMediaType ->
            Encode.string "Unsupported media type"



