{-
   Persona
   KSF Media unified login service

   The version of the OpenAPI document: 1.3.0

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git
   Do not edit this file manually.
-}


module Data.InlineResponse4032EmailNotAuthorized exposing (InlineResponse4032EmailNotAuthorized, Description(..), decoder, encode)

import Dict exposing (Dict)
import Json.Decode as Decode exposing (Decoder)
import Json.Decode.Pipeline exposing (optional, required)
import Json.Encode as Encode


type alias InlineResponse4032EmailNotAuthorized =
    { description : Maybe (Description)
    }


type Description
    = EmailAddressNotAuthorizedByTheUserOnTheSocialSite



decoder : Decoder InlineResponse4032EmailNotAuthorized
decoder =
    Decode.succeed InlineResponse4032EmailNotAuthorized
        |> optional "description" (Decode.nullable descriptionDecoder) Nothing



encode : InlineResponse4032EmailNotAuthorized -> Encode.Value
encode model =
    Encode.object
        [ ( "description", Maybe.withDefault Encode.null (Maybe.map encodeDescription model.description) )

        ]



descriptionDecoder : Decoder Description
descriptionDecoder =
    Decode.string
        |> Decode.andThen
            (\str ->
                case str of
                    "Email address not authorized by the user on the social site." ->
                        Decode.succeed EmailAddressNotAuthorizedByTheUserOnTheSocialSite

                    other ->
                        Decode.fail <| "Unknown type: " ++ other
            )



encodeDescription : Description -> Encode.Value
encodeDescription model =
    case model of
        EmailAddressNotAuthorizedByTheUserOnTheSocialSite ->
            Encode.string "Email address not authorized by the user on the social site."



