{-
   Persona
   KSF Media unified login service

   The version of the OpenAPI document: 1.3.0

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git
   Do not edit this file manually.
-}


module Data.InlineResponse403InvalidCredentials exposing (InlineResponse403InvalidCredentials, Description(..), decoder, encode)

import Dict exposing (Dict)
import Json.Decode as Decode exposing (Decoder)
import Json.Decode.Pipeline exposing (optional, required)
import Json.Encode as Encode


type alias InlineResponse403InvalidCredentials =
    { description : Maybe (Description)
    }


type Description
    = WrongUsernameOrPassword



decoder : Decoder InlineResponse403InvalidCredentials
decoder =
    Decode.succeed InlineResponse403InvalidCredentials
        |> optional "description" (Decode.nullable descriptionDecoder) Nothing



encode : InlineResponse403InvalidCredentials -> Encode.Value
encode model =
    Encode.object
        [ ( "description", Maybe.withDefault Encode.null (Maybe.map encodeDescription model.description) )

        ]



descriptionDecoder : Decoder Description
descriptionDecoder =
    Decode.string
        |> Decode.andThen
            (\str ->
                case str of
                    "Wrong username or password" ->
                        Decode.succeed WrongUsernameOrPassword

                    other ->
                        Decode.fail <| "Unknown type: " ++ other
            )



encodeDescription : Description -> Encode.Value
encodeDescription model =
    case model of
        WrongUsernameOrPassword ->
            Encode.string "Wrong username or password"



