{-
   Persona
   KSF Media unified login service

   The version of the OpenAPI document: 1.3.0

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git
   Do not edit this file manually.
-}


module Data.InlineResponse4032OauthFailed exposing (InlineResponse4032OauthFailed, Description(..), decoder, encode)

import Dict exposing (Dict)
import Json.Decode as Decode exposing (Decoder)
import Json.Decode.Pipeline exposing (optional, required)
import Json.Encode as Encode


type alias InlineResponse4032OauthFailed =
    { description : Maybe (Description)
    }


type Description
    = SomethingWrongHappenedWhileAuthenticatingJanrainWithOAuth



decoder : Decoder InlineResponse4032OauthFailed
decoder =
    Decode.succeed InlineResponse4032OauthFailed
        |> optional "description" (Decode.nullable descriptionDecoder) Nothing



encode : InlineResponse4032OauthFailed -> Encode.Value
encode model =
    Encode.object
        [ ( "description", Maybe.withDefault Encode.null (Maybe.map encodeDescription model.description) )

        ]



descriptionDecoder : Decoder Description
descriptionDecoder =
    Decode.string
        |> Decode.andThen
            (\str ->
                case str of
                    "Something wrong happened while authenticating Janrain with OAuth" ->
                        Decode.succeed SomethingWrongHappenedWhileAuthenticatingJanrainWithOAuth

                    other ->
                        Decode.fail <| "Unknown type: " ++ other
            )



encodeDescription : Description -> Encode.Value
encodeDescription model =
    case model of
        SomethingWrongHappenedWhileAuthenticatingJanrainWithOAuth ->
            Encode.string "Something wrong happened while authenticating Janrain with OAuth"



