{-
   Persona
   KSF Media unified login service

   The version of the OpenAPI document: 1.3.0

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git
   Do not edit this file manually.
-}


module Data.InlineResponse500InternalServerError exposing (InlineResponse500InternalServerError, Description(..), decoder, encode)

import Dict exposing (Dict)
import Json.Decode as Decode exposing (Decoder)
import Json.Decode.Pipeline exposing (optional, required)
import Json.Encode as Encode


type alias InlineResponse500InternalServerError =
    { description : Maybe (Description)
    }


type Description
    = InternalServerError



decoder : Decoder InlineResponse500InternalServerError
decoder =
    Decode.succeed InlineResponse500InternalServerError
        |> optional "description" (Decode.nullable descriptionDecoder) Nothing



encode : InlineResponse500InternalServerError -> Encode.Value
encode model =
    Encode.object
        [ ( "description", Maybe.withDefault Encode.null (Maybe.map encodeDescription model.description) )

        ]



descriptionDecoder : Decoder Description
descriptionDecoder =
    Decode.string
        |> Decode.andThen
            (\str ->
                case str of
                    "Internal server error" ->
                        Decode.succeed InternalServerError

                    other ->
                        Decode.fail <| "Unknown type: " ++ other
            )



encodeDescription : Description -> Encode.Value
encodeDescription model =
    case model of
        InternalServerError ->
            Encode.string "Internal server error"



