{-
   Persona
   KSF Media unified login service

   The version of the OpenAPI document: 1.3.0

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git
   Do not edit this file manually.
-}


module Data.LoginDataSoMe exposing (LoginDataSoMe, decoder, encode)

import Dict exposing (Dict)
import Json.Decode as Decode exposing (Decoder)
import Json.Decode.Pipeline exposing (optional, required)
import Json.Encode as Encode


type alias LoginDataSoMe =
    { provider : String
    , someToken : String
    , mergeToken : Maybe (String)
    }


decoder : Decoder LoginDataSoMe
decoder =
    Decode.succeed LoginDataSoMe
        |> required "provider" Decode.string
        |> required "someToken" Decode.string
        |> optional "mergeToken" (Decode.nullable Decode.string) Nothing



encode : LoginDataSoMe -> Encode.Value
encode model =
    Encode.object
        [ ( "provider", Encode.string model.provider )
        , ( "someToken", Encode.string model.someToken )
        , ( "mergeToken", Maybe.withDefault Encode.null (Maybe.map Encode.string model.mergeToken) )

        ]


