{-
   Persona
   KSF Media unified login service

   The version of the OpenAPI document: 1.3.0

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git
   Do not edit this file manually.
-}


module Data.LoginResponse exposing (LoginResponse, decoder, encode)

import Uuid exposing (Uuid)
import Dict exposing (Dict)
import Json.Decode as Decode exposing (Decoder)
import Json.Decode.Pipeline exposing (optional, required)
import Json.Encode as Encode


type alias LoginResponse =
    { token : String
    , ssoCode : Maybe (String)
    , uuid : Uuid
    }


decoder : Decoder LoginResponse
decoder =
    Decode.succeed LoginResponse
        |> required "token" Decode.string
        |> optional "ssoCode" (Decode.nullable Decode.string) Nothing
        |> required "uuid" Uuid.decoder



encode : LoginResponse -> Encode.Value
encode model =
    Encode.object
        [ ( "token", Encode.string model.token )
        , ( "ssoCode", Maybe.withDefault Encode.null (Maybe.map Encode.string model.ssoCode) )
        , ( "uuid", Uuid.encode model.uuid )

        ]


