{-
   Persona
   KSF Media unified login service

   The version of the OpenAPI document: 1.3.0

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git
   Do not edit this file manually.
-}


module Data.LoginData exposing (LoginData, decoder, encode)

import Dict exposing (Dict)
import Json.Decode as Decode exposing (Decoder)
import Json.Decode.Pipeline exposing (optional, required)
import Json.Encode as Encode


type alias LoginData =
    { username : String
    , password : String
    , mergeToken : Maybe (String)
    }


decoder : Decoder LoginData
decoder =
    Decode.succeed LoginData
        |> required "username" Decode.string
        |> required "password" Decode.string
        |> optional "mergeToken" (Decode.nullable Decode.string) Nothing



encode : LoginData -> Encode.Value
encode model =
    Encode.object
        [ ( "username", Encode.string model.username )
        , ( "password", Encode.string model.password )
        , ( "mergeToken", Maybe.withDefault Encode.null (Maybe.map Encode.string model.mergeToken) )

        ]


