{-
   Persona
   KSF Media unified login service

   The version of the OpenAPI document: 1.3.0

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git
   Do not edit this file manually.
-}


module Data.PackageOffer exposing (PackageOffer, decoder, encode)

import Dict exposing (Dict)
import Json.Decode as Decode exposing (Decoder)
import Json.Decode.Pipeline exposing (optional, required)
import Json.Encode as Encode


type alias PackageOffer =
    { months : Int
    , totalPrice : Int
    , monthlyPrice : Int
    }


decoder : Decoder PackageOffer
decoder =
    Decode.succeed PackageOffer
        |> required "months" Decode.int
        |> required "totalPrice" Decode.int
        |> required "monthlyPrice" Decode.int



encode : PackageOffer -> Encode.Value
encode model =
    Encode.object
        [ ( "months", Encode.int model.months )
        , ( "totalPrice", Encode.int model.totalPrice )
        , ( "monthlyPrice", Encode.int model.monthlyPrice )

        ]


