{-
   Persona
   KSF Media unified login service

   The version of the OpenAPI document: 1.3.0

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git
   Do not edit this file manually.
-}


module Data.Package exposing (Package, decoder, encode)

import Data.Paper as Paper exposing (Paper)
import Data.Product as Product exposing (Product)
import Data.PackageOffer as PackageOffer exposing (PackageOffer)
import Data.Campaign as Campaign exposing (Campaign)
import DateOnly exposing (DateOnly)
import Data.PackageDescription as PackageDescription exposing (PackageDescription)
import Dict exposing (Dict)
import Json.Decode as Decode exposing (Decoder)
import Json.Decode.Pipeline exposing (optional, required)
import Json.Encode as Encode


type alias Package =
    { id : String
    , name : String
    , paper : Paper
    , digitalOnly : Bool
    , products : (List Product)
    , offers : (List PackageOffer)
    , campaigns : (List Campaign)
    , nextDelivery : Maybe (DateOnly)
    , description : Maybe (PackageDescription)
    }


decoder : Decoder Package
decoder =
    Decode.succeed Package
        |> required "id" Decode.string
        |> required "name" Decode.string
        |> required "paper" Paper.decoder
        |> required "digitalOnly" Decode.bool
        |> required "products" (Decode.list Product.decoder)
        |> required "offers" (Decode.list PackageOffer.decoder)
        |> required "campaigns" (Decode.list Campaign.decoder)
        |> optional "nextDelivery" (Decode.nullable DateOnly.decoder) Nothing
        |> optional "description" (Decode.nullable PackageDescription.decoder) Nothing



encode : Package -> Encode.Value
encode model =
    Encode.object
        [ ( "id", Encode.string model.id )
        , ( "name", Encode.string model.name )
        , ( "paper", Paper.encode model.paper )
        , ( "digitalOnly", Encode.bool model.digitalOnly )
        , ( "products", (Encode.list Product.encode) model.products )
        , ( "offers", (Encode.list PackageOffer.encode) model.offers )
        , ( "campaigns", (Encode.list Campaign.encode) model.campaigns )
        , ( "nextDelivery", Maybe.withDefault Encode.null (Maybe.map DateOnly.encode model.nextDelivery) )
        , ( "description", Maybe.withDefault Encode.null (Maybe.map PackageDescription.encode model.description) )

        ]


