{-
   Persona
   KSF Media unified login service

   The version of the OpenAPI document: 1.3.0

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git
   Do not edit this file manually.
-}


module Data.PackageDescription exposing (PackageDescription, decoder, encode)

import Data.DescriptionFrequency as DescriptionFrequency exposing (DescriptionFrequency)
import Dict exposing (Dict)
import Json.Decode as Decode exposing (Decoder)
import Json.Decode.Pipeline exposing (optional, required)
import Json.Encode as Encode


type alias PackageDescription =
    { brand : String
    , brandLong : String
    , descShort : String
    , descLong : String
    , url : String
    , days : String
    , weekdays : String
    , frequency : DescriptionFrequency
    , includes : (List String)
    }


decoder : Decoder PackageDescription
decoder =
    Decode.succeed PackageDescription
        |> required "brand" Decode.string
        |> required "brandLong" Decode.string
        |> required "descShort" Decode.string
        |> required "descLong" Decode.string
        |> required "url" Decode.string
        |> required "days" Decode.string
        |> required "weekdays" Decode.string
        |> required "frequency" DescriptionFrequency.decoder
        |> required "includes" (Decode.list Decode.string)



encode : PackageDescription -> Encode.Value
encode model =
    Encode.object
        [ ( "brand", Encode.string model.brand )
        , ( "brandLong", Encode.string model.brandLong )
        , ( "descShort", Encode.string model.descShort )
        , ( "descLong", Encode.string model.descLong )
        , ( "url", Encode.string model.url )
        , ( "days", Encode.string model.days )
        , ( "weekdays", Encode.string model.weekdays )
        , ( "frequency", DescriptionFrequency.encode model.frequency )
        , ( "includes", (Encode.list Encode.string) model.includes )

        ]


