{-
   Persona
   KSF Media unified login service

   The version of the OpenAPI document: 1.3.0

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git
   Do not edit this file manually.
-}


module Data.Paper exposing (Paper, decoder, encode)

import Dict exposing (Dict)
import Json.Decode as Decode exposing (Decoder)
import Json.Decode.Pipeline exposing (optional, required)
import Json.Encode as Encode


type alias Paper =
    { code : String
    , name : String
    }


decoder : Decoder Paper
decoder =
    Decode.succeed Paper
        |> required "code" Decode.string
        |> required "name" Decode.string



encode : Paper -> Encode.Value
encode model =
    Encode.object
        [ ( "code", Encode.string model.code )
        , ( "name", Encode.string model.name )

        ]


