{-
   Persona
   KSF Media unified login service

   The version of the OpenAPI document: 1.3.0

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git
   Do not edit this file manually.
-}


module Data.PendingAddressChange exposing (PendingAddressChange, decoder, encode)

import Data.DeliveryAddress as DeliveryAddress exposing (DeliveryAddress)
import DateOnly exposing (DateOnly)
import DateOnly exposing (DateOnly)
import Dict exposing (Dict)
import Json.Decode as Decode exposing (Decoder)
import Json.Decode.Pipeline exposing (optional, required)
import Json.Encode as Encode


type alias PendingAddressChange =
    { address : DeliveryAddress
    , startDate : DateOnly
    , endDate : DateOnly
    , type_ : String
    }


decoder : Decoder PendingAddressChange
decoder =
    Decode.succeed PendingAddressChange
        |> required "address" DeliveryAddress.decoder
        |> required "startDate" DateOnly.decoder
        |> required "endDate" DateOnly.decoder
        |> required "type" Decode.string



encode : PendingAddressChange -> Encode.Value
encode model =
    Encode.object
        [ ( "address", DeliveryAddress.encode model.address )
        , ( "startDate", DateOnly.encode model.startDate )
        , ( "endDate", DateOnly.encode model.endDate )
        , ( "type", Encode.string model.type_ )

        ]


