{-
   Persona
   KSF Media unified login service

   The version of the OpenAPI document: 1.3.0

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git
   Do not edit this file manually.
-}


module Data.SubscriptionPauseDates exposing (SubscriptionPauseDates, decoder, encode)

import DateOnly exposing (DateOnly)
import DateOnly exposing (DateOnly)
import Dict exposing (Dict)
import Json.Decode as Decode exposing (Decoder)
import Json.Decode.Pipeline exposing (optional, required)
import Json.Encode as Encode


type alias SubscriptionPauseDates =
    { startDate : DateOnly
    , endDate : DateOnly
    }


decoder : Decoder SubscriptionPauseDates
decoder =
    Decode.succeed SubscriptionPauseDates
        |> required "startDate" DateOnly.decoder
        |> required "endDate" DateOnly.decoder



encode : SubscriptionPauseDates -> Encode.Value
encode model =
    Encode.object
        [ ( "startDate", DateOnly.encode model.startDate )
        , ( "endDate", DateOnly.encode model.endDate )

        ]


