{-
   Persona
   KSF Media unified login service

   The version of the OpenAPI document: 1.3.0

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git
   Do not edit this file manually.
-}


module Data.SubscriptionDates exposing (SubscriptionDates, decoder, encode)

import DateOnly exposing (DateOnly)
import DateOnly exposing (DateOnly)
import DateOnly exposing (DateOnly)
import DateOnly exposing (DateOnly)
import DateOnly exposing (DateOnly)
import DateOnly exposing (DateOnly)
import Dict exposing (Dict)
import Json.Decode as Decode exposing (Decoder)
import Json.Decode.Pipeline exposing (optional, required)
import Json.Encode as Encode


type alias SubscriptionDates =
    { lenMonths : Maybe (Int)
    , lenDays : Maybe (Int)
    , start : DateOnly
    , end : Maybe (DateOnly)
    , unpaidBreak : Maybe (DateOnly)
    , invoicingStart : Maybe (DateOnly)
    , paidUntil : Maybe (DateOnly)
    , suspend : Maybe (DateOnly)
    }


decoder : Decoder SubscriptionDates
decoder =
    Decode.succeed SubscriptionDates
        |> optional "lenMonths" (Decode.nullable Decode.int) Nothing
        |> optional "lenDays" (Decode.nullable Decode.int) Nothing
        |> required "start" DateOnly.decoder
        |> optional "end" (Decode.nullable DateOnly.decoder) Nothing
        |> optional "unpaidBreak" (Decode.nullable DateOnly.decoder) Nothing
        |> optional "invoicingStart" (Decode.nullable DateOnly.decoder) Nothing
        |> optional "paidUntil" (Decode.nullable DateOnly.decoder) Nothing
        |> optional "suspend" (Decode.nullable DateOnly.decoder) Nothing



encode : SubscriptionDates -> Encode.Value
encode model =
    Encode.object
        [ ( "lenMonths", Maybe.withDefault Encode.null (Maybe.map Encode.int model.lenMonths) )
        , ( "lenDays", Maybe.withDefault Encode.null (Maybe.map Encode.int model.lenDays) )
        , ( "start", DateOnly.encode model.start )
        , ( "end", Maybe.withDefault Encode.null (Maybe.map DateOnly.encode model.end) )
        , ( "unpaidBreak", Maybe.withDefault Encode.null (Maybe.map DateOnly.encode model.unpaidBreak) )
        , ( "invoicingStart", Maybe.withDefault Encode.null (Maybe.map DateOnly.encode model.invoicingStart) )
        , ( "paidUntil", Maybe.withDefault Encode.null (Maybe.map DateOnly.encode model.paidUntil) )
        , ( "suspend", Maybe.withDefault Encode.null (Maybe.map DateOnly.encode model.suspend) )

        ]


