{-
   Persona
   KSF Media unified login service

   The version of the OpenAPI document: 1.3.0

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git
   Do not edit this file manually.
-}


module Data.UserUpdate exposing (UserUpdate, decoder, encode)

import Data.UserUpdateAddress as UserUpdateAddress exposing (UserUpdateAddress)
import Dict exposing (Dict)
import Json.Decode as Decode exposing (Decoder)
import Json.Decode.Pipeline exposing (optional, required)
import Json.Encode as Encode


type alias UserUpdate =
    { firstName : Maybe (String)
    , lastName : Maybe (String)
    , address : Maybe (UserUpdateAddress)
    }


decoder : Decoder UserUpdate
decoder =
    Decode.succeed UserUpdate
        |> optional "firstName" (Decode.nullable Decode.string) Nothing
        |> optional "lastName" (Decode.nullable Decode.string) Nothing
        |> optional "address" (Decode.nullable UserUpdateAddress.decoder) Nothing



encode : UserUpdate -> Encode.Value
encode model =
    Encode.object
        [ ( "firstName", Maybe.withDefault Encode.null (Maybe.map Encode.string model.firstName) )
        , ( "lastName", Maybe.withDefault Encode.null (Maybe.map Encode.string model.lastName) )
        , ( "address", Maybe.withDefault Encode.null (Maybe.map UserUpdateAddress.encode model.address) )

        ]


