{-
   Persona
   KSF Media unified login service

   The version of the OpenAPI document: 1.3.0

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git
   Do not edit this file manually.
-}


module Data.UserUpdateAddress exposing (UserUpdateAddress, decoder, encode)

import Dict exposing (Dict)
import Json.Decode as Decode exposing (Decoder)
import Json.Decode.Pipeline exposing (optional, required)
import Json.Encode as Encode


type alias UserUpdateAddress =
    { countryCode : String
    , zipCode : String
    , streetAddress : String
    }


decoder : Decoder UserUpdateAddress
decoder =
    Decode.succeed UserUpdateAddress
        |> required "countryCode" Decode.string
        |> required "zipCode" Decode.string
        |> required "streetAddress" Decode.string



encode : UserUpdateAddress -> Encode.Value
encode model =
    Encode.object
        [ ( "countryCode", Encode.string model.countryCode )
        , ( "zipCode", Encode.string model.zipCode )
        , ( "streetAddress", Encode.string model.streetAddress )

        ]


